.TH TYPEOF 1 "10 April 2016" "0.55" "typeof function"

.SH NAME
typeof \- variables typing and dumping

.SH SYNOPSIS
.B typeof
.RB [ " \-t " ]
[
.I NAME
]

.SH DESCRIPTION
Started as a function mostly used to pretty dump array to the screen,
now a function to type and qualify supplied parameter.
Still, when used with variable as parameter it outputs
information about it, such as its value and attributes.

.SH OPTIONS
.TP
.B \-b --brief
Return the type, as a single word.
.br
.PP
Returned types:
.br
.I scalar
for a set variable
.br
.I indexed
for an indexed array
.br
.I associative
for an associative array
.br
If parameter is a shell keyword, returned types are those returned by the
.B type
builtin:
.br
.IR alias , keyword , function , builtin , file .

.SH PARAMETERS
.I NAME
Parameter can be a bare word, identifier, variable, array, shell keyword, etc. If parameter is an identifier (variable's name) it must be passed without the $ sign.

.SH "RETURN STATUS"
.B 0
Successful program execution.
.br
.B 1
Usage or syntax error.
.br
.B 2
Parameter is of no significance.

.SH EXAMPLE
$ typeof -b BASH_ALIASES   # outputs: `associative'
$ typeof BASH_VERSINFO     # dumps array BASH_VERSINFO

.SH AUTHORS
Ilic Ivan <ilicivan@zoho.com>
.br
<https://github.com/mandober/typeof>

.SH LICENSE
MIT